In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (from ucimlrepo) (2.3.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (from ucimlrepo) (2025.8.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\personal\appdata\roaming\python\python311\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\personal\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\personal\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
covertype = fetch_ucirepo(id=31) 
  
# data (as pandas dataframes) 
X = covertype.data.features 
y = covertype.data.targets 
  
# metadata 
print(covertype.metadata) 
  
# variable information 
print(covertype.variables)

{'uci_id': 31, 'name': 'Covertype', 'repository_url': 'https://archive.ics.uci.edu/dataset/31/covertype', 'data_url': 'https://archive.ics.uci.edu/static/public/31/data.csv', 'abstract': 'Classification of pixels into 7 forest cover types based on attributes such as elevation, aspect, slope, hillshade, soil-type, and more.', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 581012, 'num_features': 54, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': ['Cover_Type'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1998, 'last_updated': 'Sat Mar 16 2024', 'dataset_doi': '10.24432/C50K5N', 'creators': ['Jock Blackard'], 'intro_paper': None, 'additional_info': {'summary': 'Predicting forest cover type from cartographic variables only (no remotely sensed data).  The actual forest cover type for a given observation (30 x 30 meter cell) was determined from US Forest Service (USFS) Region 2 Resource Information System (RIS) data.  Independent variables were derived from data originally obtained from US Geological Survey (USGS) and USFS data.  Data is in raw form (not scaled) and contains binary (0 or 1) columns of data for qualitative independent variables (wilderness areas and soil types).\r\n\r\nThis study area includes four wilderness areas located in the Roosevelt National Forest of northern Colorado.  These areas represent forests with minimal human-caused disturbances, so that existing forest cover types are more a result of ecological processes rather than forest management practices.\r\n\r\nSome background information for these four wilderness areas: Neota (area 2) probably has the highest mean elevational value of the 4 wilderness areas. Rawah (area 1) and Comanche Peak (area 3) would have a lower mean elevational value, while Cache la Poudre (area 4) would have the lowest mean elevational value. \r\n\r\nAs for primary major tree species in these areas, Neota would have spruce/fir (type 1), while Rawah and Comanche Peak would probably have lodgepole pine (type 2) as their primary species, followed by spruce/fir and aspen (type 5). Cache la Poudre would tend to have Ponderosa pine (type 3), Douglas-fir (type 6), and cottonwood/willow (type 4).  \r\n\r\nThe Rawah and Comanche Peak areas would tend to be more typical of the overall dataset than either the Neota or Cache la Poudre, due to their assortment of tree species and range of predictive variable values (elevation, etc.)  Cache la Poudre would probably  be more unique than the others, due to its relatively low  elevation range and species composition. ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Given is the attribute name, attribute type, the measurement unit and a brief description.  The forest cover type is the classification  problem.  The order of this listing corresponds to the order of numerals along the rows of the database.\r\n\r\nName / Data Type / Measurement / Description\r\n\r\nElevation / quantitative /meters / Elevation in meters\r\nAspect / quantitative / azimuth / Aspect in degrees azimuth\r\nSlope / quantitative / degrees / Slope in degrees\r\nHorizontal_Distance_To_Hydrology / quantitative / meters / Horz Dist to nearest surface water features\r\nVertical_Distance_To_Hydrology / quantitative / meters / Vert Dist to nearest surface water features\r\nHorizontal_Distance_To_Roadways / quantitative / meters / Horz Dist to nearest roadway\r\nHillshade_9am / quantitative / 0 to 255 index / Hillshade index at 9am, summer solstice\r\nHillshade_Noon / quantitative / 0 to 255 index / Hillshade index at noon, summer soltice\r\nHillshade_3pm / quantitative / 0 to 255 index / Hillshade index at 3pm, summer solstice\r\nHorizontal_Distance_To_Fire_Points / quantitative / meters / Horz Dist to nearest wildfire ignition points\r\nWilderness_Area (4 binary columns) / qualitative / 0 (absence) or 1 (presence) / Wilderness area designation\r\nSoil_Type (40 binary columns) / qualitative / 0 (absence) or 1 (presence) / Soil Type designation\r\nCover_Type (7 types) / integer / 1 to 7 / Forest Cover Type designation', 'citation': None}}
                                  name     role     type demographic  \
0                            Elevation  Feature  Integer        None
1                               Aspect  Feature  Integer        None
2                                Slope  Feature  Integer        None
3     Horizontal_Distance_To_Hydrology  Feature  Integer        None
4       Vertical_Distance_To_Hydrology  Feature  Integer        None
5      Horizontal_Distance_To_Roadways  Feature  Integer        None
6                        Hillshade_9am  Feature  Integer        None
7                       Hillshade_Noon  Feature  Integer        None
8                        Hillshade_3pm  Feature  Integer        None
9   Horizontal_Distance_To_Fire_Points  Feature  Integer        None
10                    Wilderness_Area1  Feature  Integer        None
11                          Soil_Type1  Feature  Integer        None
12                          Soil_Type2  Feature  Integer        None
13                          Soil_Type3  Feature  Integer        None
14                          Soil_Type4  Feature  Integer        None
15                          Soil_Type5  Feature  Integer        None
16                          Soil_Type6  Feature  Integer        None
17                          Soil_Type7  Feature  Integer        None
18                          Soil_Type8  Feature  Integer        None
19                          Soil_Type9  Feature  Integer        None
20                         Soil_Type10  Feature  Integer        None
21                         Soil_Type11  Feature  Integer        None
22                         Soil_Type12  Feature  Integer        None
23                         Soil_Type13  Feature  Integer        None
24                         Soil_Type14  Feature  Integer        None
25                         Soil_Type15  Feature  Integer        None
26                         Soil_Type16  Feature  Integer        None
27                         Soil_Type17  Feature  Integer        None
28                         Soil_Type18  Feature  Integer        None
29                         Soil_Type19  Feature  Integer        None
30                         Soil_Type20  Feature  Integer        None
31                         Soil_Type21  Feature  Integer        None
32                         Soil_Type22  Feature  Integer        None
33                         Soil_Type23  Feature  Integer        None
34                         Soil_Type24  Feature  Integer        None
35                         Soil_Type25  Feature  Integer        None
36                         Soil_Type26  Feature  Integer        None
37                         Soil_Type27  Feature  Integer        None
38                         Soil_Type28  Feature  Integer        None
39                         Soil_Type29  Feature  Integer        None
40                         Soil_Type30  Feature  Integer        None
41                         Soil_Type31  Feature  Integer        None
42                         Soil_Type32  Feature  Integer        None
43                         Soil_Type33  Feature  Integer        None
44                         Soil_Type34  Feature  Integer        None
45                         Soil_Type35  Feature  Integer        None
46                         Soil_Type36  Feature  Integer        None
47                         Soil_Type37  Feature  Integer        None
48                         Soil_Type38  Feature  Integer        None
49                         Soil_Type39  Feature  Integer        None
50                         Soil_Type40  Feature  Integer        None
51                          Cover_Type   Target  Integer        None
52                    Wilderness_Area2  Feature  Integer        None
53                    Wilderness_Area3  Feature  Integer        None
54                    Wilderness_Area4  Feature  Integer        None

   description units missing_values
0         None  None             no
1         None  None             no
2         None  None             no
3         None  None             no
4         None  None             no
5         None  None             no
6         None  None             no
7         None  None             no
8         None  None             no
9         None  None             no
10        None  None             no
11        None  None             no
12        None  None             no
13        None  None             no
14        None  None             no
15        None  None             no
16        None  None             no
17        None  None             no
18        None  None             no
19        None  None             no
20        None  None             no
21        None  None             no
22        None  None             no
23        None  None             no
24        None  None             no
25        None  None             no
26        None  None             no
27        None  None             no
28        None  None             no
29        None  None             no
30        None  None             no
31        None  None             no
32        None  None             no
33        None  None             no
34        None  None             no
35        None  None             no
36        None  None             no
37        None  None             no
38        None  None             no
39        None  None             no
40        None  None             no
41        None  None             no
42        None  None             no
43        None  None             no
44        None  None             no
45        None  None             no
46        None  None             no
47        None  None             no
48        None  None             no
49        None  None             no
50        None  None             no
51        None  None             no
52        None  None             no
53        None  None             no
54        None  None             no

In [14]:
X

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,1,0
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,1,0
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,1,0
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,1,0
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,1,0

In [5]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 54 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           581012 non-null  int64
 1   Aspect                              581012 non-null  int64
 2   Slope                               581012 non-null  int64
 3   Horizontal_Distance_To_Hydrology    581012 non-null  int64
 4   Vertical_Distance_To_Hydrology      581012 non-null  int64
 5   Horizontal_Distance_To_Roadways     581012 non-null  int64
 6   Hillshade_9am                       581012 non-null  int64
 7   Hillshade_Noon                      581012 non-null  int64
 8   Hillshade_3pm                       581012 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  581012 non-null  int64
 10  Wilderness_Area1                    581012 non-null  int64
 11  Soil_Type1                          581012 non-null  int64
 12  Soil_Type2                          581012 non-null  int64
 13  Soil_Type3                          581012 non-null  int64
 14  Soil_Type4                          581012 non-null  int64
 15  Soil_Type5                          581012 non-null  int64
 16  Soil_Type6                          581012 non-null  int64
 17  Soil_Type7                          581012 non-null  int64
 18  Soil_Type8                          581012 non-null  int64
 19  Soil_Type9                          581012 non-null  int64
 20  Soil_Type10                         581012 non-null  int64
 21  Soil_Type11                         581012 non-null  int64
 22  Soil_Type12                         581012 non-null  int64
 23  Soil_Type13                         581012 non-null  int64
 24  Soil_Type14                         581012 non-null  int64
 25  Soil_Type15                         581012 non-null  int64
 26  Soil_Type16                         581012 non-null  int64
 27  Soil_Type17                         581012 non-null  int64
 28  Soil_Type18                         581012 non-null  int64
 29  Soil_Type19                         581012 non-null  int64
 30  Soil_Type20                         581012 non-null  int64
 31  Soil_Type21                         581012 non-null  int64
 32  Soil_Type22                         581012 non-null  int64
 33  Soil_Type23                         581012 non-null  int64
 34  Soil_Type24                         581012 non-null  int64
 35  Soil_Type25                         581012 non-null  int64
 36  Soil_Type26                         581012 non-null  int64
 37  Soil_Type27                         581012 non-null  int64
 38  Soil_Type28                         581012 non-null  int64
 39  Soil_Type29                         581012 non-null  int64
 40  Soil_Type30                         581012 non-null  int64
 41  Soil_Type31                         581012 non-null  int64
 42  Soil_Type32                         581012 non-null  int64
 43  Soil_Type33                         581012 non-null  int64
 44  Soil_Type34                         581012 non-null  int64
 45  Soil_Type35                         581012 non-null  int64
 46  Soil_Type36                         581012 non-null  int64
 47  Soil_Type37                         581012 non-null  int64
 48  Soil_Type38                         581012 non-null  int64
 49  Soil_Type39                         581012 non-null  int64
 50  Soil_Type40                         581012 non-null  int64
 51  Wilderness_Area2                    581012 non-null  int64
 52  Wilderness_Area3                    581012 non-null  int64
 53  Wilderness_Area4                    581012 non-null  int64
dtypes: int64(54)
memory usage: 239.4 MB

In [10]:
soil_type = [
"1", "C2702", "Cathedral family - Rock outcrop complex, extremely stony.",
"2", "C2703", "Vanet - Ratake families complex, very stony.",
"3", "C2704", "Haploborolis - Rock outcrop complex, rubbly.",
"4", "C2705", "Ratake family - Rock outcrop complex, rubbly.",
"5", "C2706", "Vanet family - Rock outcrop complex complex, rubbly.",
"6", "C2717", "Vanet - Wetmore families - Rock outcrop complex, stony.",
"7", "C3501", "Gothic family.",
"8", "C3502", "Supervisor - Limber families complex.",
"9", "C4201", "Troutville family, very stony.",
"10", "C4703", "Bullwark - Catamount families - Rock outcrop complex, rubbly.",
"11", "C4704", "Bullwark - Catamount families - Rock land complex, rubbly.",
"12", "C4744", "Legault family - Rock land complex, stony.",
"13", "C4758", "Catamount family - Rock land - Bullwark family complex, rubbly.",
"14", "C5101", "Pachic Argiborolis - Aquolis complex.",
"15", "C5151", "unspecified in the USFS Soil and ELU Survey.",
"16", "C6101", "Cryaquolis - Cryoborolis complex.",
"17", "C6102", "Gateview family - Cryaquolis complex.",
"18", "C6731", "Rogert family, very stony.",
"19", "C7101", "Typic Cryaquolis - Borohemists complex.",
"20", "C7102", "Typic Cryaquepts - Typic Cryaquolls complex.",
"21", "C7103", "Typic Cryaquolls - Leighcan family, till substratum complex.",
"22", "C7201", "Leighcan family, till substratum, extremely bouldery.",
"23", "C7202", "Leighcan family, till substratum - Typic Cryaquolls complex.",
"24", "C7700", "Leighcan family, extremely stony.",
"25", "C7701", "Leighcan family, warm, extremely stony.",
"26", "C7702", "Granile - Catamount families complex, very stony.",
"27", "C7709", "Leighcan family, warm - Rock outcrop complex, extremely stony.",
"28", "C7710", "Leighcan family - Rock outcrop complex, extremely stony.",
"29", "C7745", "Como - Legault families complex, extremely stony.",
"30", "C7746", "Como family - Rock land - Legault family complex, extremely stony.",
"31", "C7755", "Leighcan - Catamount families complex, extremely stony.",
"32", "C7756", "Catamount family - Rock outcrop - Leighcan family complex, extremely stony.",
"33", "C7757", "Leighcan - Catamount families - Rock outcrop complex, extremely stony.",
"34", "C7790", "Cryorthents - Rock land complex, extremely stony.",
"35", "C8703", "Cryumbrepts - Rock outcrop - Cryaquepts complex.",
"36", "C8707", "Bross family - Rock land - Cryumbrepts complex, extremely stony.",
"37", "C8708", "Rock outcrop - Cryumbrepts - Cryorthents complex, extremely stony.",
"38", "C8771", "Leighcan - Moran families - Cryaquolls complex, extremely stony.",
"39", "C8772", "Moran family - Cryorthents - Leighcan family complex, extremely stony.",
"40", "C8776", "Moran family - Cryorthents - Rock land complex, extremely stony.",
]

wilderness_area = [
"Rawah", "Rawah Wilderness Area",
"Neota", "Neota Wilderness Area",
"Commanche", "Comanche Peak Wilderness Area",
"Cache", "Cache la Poudre Wilderness Area"
]

In [11]:
df = pd.concat([X, y], axis=1)

In [12]:
df

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,1,0,3
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,1,0,3
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,1,0,3
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,1,0,3
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,1,0,3

In [13]:
soil = df.iloc[:, 14:54].apply(
    lambda x: soil_type[1::3][x.to_numpy().nonzero()[0][0]],
    axis=1
)
soil

0         C7702
1         C7702
2         C4201
3         C7709
4         C7702
          ...
581007    C8772
581008    C8772
581009    C8772
581010    C8772
581011    C8772
Length: 581012, dtype: object

In [14]:
wilderness_cols = [c for c in df.columns if "Wilderness_Area" in c]

wilderness = df[wilderness_cols].apply(
    lambda x: wilderness_area[0::2][x.to_numpy().nonzero()[0][0]],
    axis=1
)

wilderness

0             Rawah
1             Rawah
2             Rawah
3             Rawah
4             Rawah
            ...
581007    Commanche
581008    Commanche
581009    Commanche
581010    Commanche
581011    Commanche
Length: 581012, dtype: object

In [15]:
df['Cover_Type'] = df['Cover_Type'] - 1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 55 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           581012 non-null  int64
 1   Aspect                              581012 non-null  int64
 2   Slope                               581012 non-null  int64
 3   Horizontal_Distance_To_Hydrology    581012 non-null  int64
 4   Vertical_Distance_To_Hydrology      581012 non-null  int64
 5   Horizontal_Distance_To_Roadways     581012 non-null  int64
 6   Hillshade_9am                       581012 non-null  int64
 7   Hillshade_Noon                      581012 non-null  int64
 8   Hillshade_3pm                       581012 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  581012 non-null  int64
 10  Wilderness_Area1                    581012 non-null  int64
 11  Soil_Type1                          581012 non-null  int64
 12  Soil_Type2                          581012 non-null  int64
 13  Soil_Type3                          581012 non-null  int64
 14  Soil_Type4                          581012 non-null  int64
 15  Soil_Type5                          581012 non-null  int64
 16  Soil_Type6                          581012 non-null  int64
 17  Soil_Type7                          581012 non-null  int64
 18  Soil_Type8                          581012 non-null  int64
 19  Soil_Type9                          581012 non-null  int64
 20  Soil_Type10                         581012 non-null  int64
 21  Soil_Type11                         581012 non-null  int64
 22  Soil_Type12                         581012 non-null  int64
 23  Soil_Type13                         581012 non-null  int64
 24  Soil_Type14                         581012 non-null  int64
 25  Soil_Type15                         581012 non-null  int64
 26  Soil_Type16                         581012 non-null  int64
 27  Soil_Type17                         581012 non-null  int64
 28  Soil_Type18                         581012 non-null  int64
 29  Soil_Type19                         581012 non-null  int64
 30  Soil_Type20                         581012 non-null  int64
 31  Soil_Type21                         581012 non-null  int64
 32  Soil_Type22                         581012 non-null  int64
 33  Soil_Type23                         581012 non-null  int64
 34  Soil_Type24                         581012 non-null  int64
 35  Soil_Type25                         581012 non-null  int64
 36  Soil_Type26                         581012 non-null  int64
 37  Soil_Type27                         581012 non-null  int64
 38  Soil_Type28                         581012 non-null  int64
 39  Soil_Type29                         581012 non-null  int64
 40  Soil_Type30                         581012 non-null  int64
 41  Soil_Type31                         581012 non-null  int64
 42  Soil_Type32                         581012 non-null  int64
 43  Soil_Type33                         581012 non-null  int64
 44  Soil_Type34                         581012 non-null  int64
 45  Soil_Type35                         581012 non-null  int64
 46  Soil_Type36                         581012 non-null  int64
 47  Soil_Type37                         581012 non-null  int64
 48  Soil_Type38                         581012 non-null  int64
 49  Soil_Type39                         581012 non-null  int64
 50  Soil_Type40                         581012 non-null  int64
 51  Wilderness_Area2                    581012 non-null  int64
 52  Wilderness_Area3                    581012 non-null  int64
 53  Wilderness_Area4                    581012 non-null  int64
 54  Cover_Type                          581012 non-null  int64
dtypes: int64(55)
memory usage: 243.8 MB

In [51]:
import os

os.listdir()

['dataset_test', 'Dockerfile.jupyter', 'test.ipynb']

In [53]:
df_test = pd.read_csv("dataset_test/dataset_test.csv")

In [ ]:
import requests
import time

def get_data():

    url = "http://get_data_api:8003/data"

    params = {
        "group_number": 3
    }

    for _ in range(10):
        try:
            response = requests.get(url, params=params)
            return response.json()
        except:
            print("Waiting for API...")
            time.sleep(3)

In [4]:
data = get_data()

In [5]:
data

{'detail': 'Ya se recolectó toda la información minima necesaria'}